spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  360977843344-ab62mfjkj6ndc0h1tgdkppb9nrj05l32.apps.googleusercontent.com
            client-secret:  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
            scope:  profile,email


